"""add elis events table

Revision ID: 6f0681eac235
Revises: 
Create Date: 2026-03-30 13:35:37.881614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f0681eac235'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elis_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('ml_class', sa.String(), nullable=True),
    sa.Column('ml_confidence', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elis_events_id'), 'elis_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_elis_events_id'), table_name='elis_events')
    op.drop_table('elis_events')
    # ### end Alembic commands ###
